project_id = "jpxnekifttziwkiiptlv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[edge_runtime]
enabled = true
port = 54323

[functions.detect]
verify_jwt = false

[functions.history]
verify_jwt = false

[realtime]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[auth.email]
enable_signup = true